# ChatColour 配置文件
# 聊天颜色插件配置文件
# 作者: PUEHMC
# GitHub: https://github.com/PUEHMC/ChatColour

# 是否为所有玩家启用颜色代码 (true = 所有人可用, false = 仅白名单/权限玩家可用)
enable-for-all: true

# 白名单玩家列表 (当enable-for-all为false时生效)
# 这些玩家即使没有chatcolour.use权限也可以使用颜色代码
whitelist:
  - "玩家1"
  - "玩家2"
  # 添加更多玩家名称...

# 颜色代码说明:
# 传统颜色代码 (&符号):
# &0 - 黑色
# &1 - 深蓝色
# &2 - 深绿色
# &3 - 深青色
# &4 - 深红色
# &5 - 紫色
# &6 - 金色
# &7 - 灰色
# &8 - 深灰色
# &9 - 蓝色
# &a - 绿色
# &b - 青色
# &c - 红色
# &d - 粉色
# &e - 黄色
# &f - 白色
# &k - 随机字符
# &l - 粗体
# &m - 删除线
# &n - 下划线
# &o - 斜体
# &r - 重置
#
# 十六进制颜色代码 (#符号，需要Minecraft 1.16+):
# #RRGGBB - 自定义RGB颜色
# 例如: #FF0000 (红色), #00FF00 (绿色), #0000FF (蓝色)
# 例如: #FFD700 (金色), #FF69B4 (粉色), #00CED1 (深青色)
#
# 混合使用示例:
# "&l#FF0000粗体红色文字&r #00FF00普通绿色文字"
# "#FFD700金色&l粗体&r #0000FF蓝色"
